production:
  url: "<%= ENV.fetch('REDIS_URL', 'redis://system-redis/1') %>"
  pool_size: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  pool_timeout: 5 # this is in seconds
  namespace: "<%= ENV['REDIS_NAMESPACE'] %>"
  sentinels: "<%= ENV['REDIS_SENTINEL_HOSTS'] %>"
  name: "<%= ENV['REDIS_SENTINEL_NAME'] %>"
  role: <%= ENV['REDIS_SENTINEL_ROLE'] %>
